sudo: false
dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:	
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-7
    - g++-7
    - clang-3.8
install:
- export FUJIN_ROOT=`pwd`
- chmod +x ./install/install_boost.sh
- ./install/install_boost.sh
- export CPATH=$CPATH:./external_libraries/boost_66_0
- make
build: make
script: make
