sudo: false
dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:	
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-7
    - g++-7
    - clang-3.8
install:
- make
build: make
script: make
