sudo: false
dist: xenial
language: cpp
python:
- "3.4"
compiler:
- gcc
os:
- linux
addons:
  apt:	
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-7
    - g++-7
    - clang-3.8
install:
- pip install --user numpy
- pip install --user h5py
- pip install --user scipy
- export FUJIN_ROOT=`pwd`
- chmod +x ./install/install_boost.sh
- ./install/install_boost.sh
- chmod +x ./install/install_hdf5.sh
- ./install/install_hdf5.sh
- export CPATH=$(CPATH):`pwd`/external_libraries/boost_1_66_0:`pwd`/external_libraries/include
- export CPLUS_INCLUDE_PATH=$(CPLUS_INCLUDE_PATH):`pwd`/external_libraries/boost_1_66_0:`pwd`/external_libraries/include
- export HDF5_LIB_PATH=`pwd`/external_libraries/lib
- export LD_LIBRARY_PATH=$(LD_LIBRARY_PATH):`pwd`/external_libraries/lib
- make SILENCE_WARNINGS=1
- cd tests
- make SILENCE_WARNINGS=1
build: make
script: make
