sudo: false
dist: xenial
language: cpp
compiler:
- gcc
os:
- linux
addons:
  apt:	
    sources:
    - ubuntu-toolchain-r-test
    - boost-latest
    packages:
    - gcc-7
    - g++-7
    - clang-3.8
install:
- export FUJIN_ROOT=`pwd`
- chmod +x ./install/install_boost.sh
- ./install/install_boost.sh
- export CPATH=$(CPATH):`pwd`/external_libraries/boost_1_66_0
- echo $CPATH
- export CPLUS_INCLUDE_PATH=$(CPLUS_INCLUDE_PATH):`pwd`/external_libraries/boost_1_66_0
- echo $CPLUS_INCLUDE_PATH
- ls
- make SILENCE_WARNINGS=1
build: make
script: make
